package com.sda.j92.academy.model;

public enum FieldOfStudyEnum {
    UNKNOWN,
    Architecture_and_Urban_Planning,
    Civil_Engineering,
    Environmental_Engineering,
    Biomedical_Engineering,
    Materials_Engineering,
    Mechanical_Engineering,
    Management_and_Production_Engineering,
    Mechatronics,
    Technical_Applications_of_the_Internet,
    Electronics_and_Telecommunications,
    Automatic_Control_and_Robotics,
    Electrical_Engineering,
    Information_Engineering,
    Power_Engineering,
    Mathematics,
    Automatic_Control_and_Management,
    Bioinformatics,
    Safety_Engineering,
    Logistics,
    Transport,
    Chemical_Technology,
    }
